name: Versioning Workflow

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get latest tag
        id: get_latest_tag
        run: |
          TAG=$(git tag --sort=-creatordate | grep '^v' | head -n 1)
          echo "Latest tag: $TAG"
          echo "latest_tag=$TAG" >> $GITHUB_ENV

      - name: Determine new tag version
        id: new_version
        run: |
          if [ -z "${{ env.latest_tag }}" ]; then
            echo "No existing tag found, using v0.1.0 as the initial version"
            echo "new_tag=v0.1.0" >> $GITHUB_ENV
          else
            # Extract the version components
            version="${{ env.latest_tag }}"
            version=${version/v/}  # Remove the 'v' prefix
            IFS='.' read -r major minor patch <<< "$version"
            new_minor=$((minor + 1))
            new_tag="v${major}.${new_minor}.0"
            echo "New tag: $new_tag"
            echo "new_tag=$new_tag" >> $GITHUB_ENV
          fi

      - name: Create new tag
        run: |
          git tag ${{ env.new_tag }}
          echo "Created tag: ${{ env.new_tag }}"

      - name: Push new tag
        run: |
          git push origin ${{ env.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
