name: Versioning Workflow

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get latest tag
        id: get_latest_tag
        run: |
          TAG=$(git tag --sort=-creatordate | grep '^v' | head -n 1)
          echo "Latest tag: $TAG"
          echo "::set-output name=latest_tag::$TAG"

      - name: Determine new tag version
        id: new_version
        run: |
          if [ -z "${{ steps.get_latest_tag.outputs.latest_tag }}" ]; then
            echo "No existing tag found, using v0.1.0 as the initial version"
            echo "::set-output name=new_tag::v0.1.0"
          else
            # Extract the version components
            IFS='.' read -r major minor patch <<< "${{ steps.get_latest_tag.outputs.latest_tag | sed 's/v//g' | sed 's/-.*//g' }}"
            new_minor=$((minor + 1))
            new_tag="v${major}.${new_minor}.0"
            echo "New tag: $new_tag"
            echo "::set-output name=new_tag::$new_tag"
          fi

      - name: Create new tag
        run: |
          git tag ${{ steps.new_version.outputs.new_tag }}
          echo "Created tag: ${{ steps.new_version.outputs.new_tag }}"

      - name: Push new tag
        run: |
          git push origin ${{ steps.new_version.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
