name: Release

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get latest tag
      id: get_latest_tag
      run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Set new tag
      id: set_new_tag
      run: |
        if [ -z "${{ env.latest_tag }}" ]; then
          echo "new_tag=v0.1.0" >> $GITHUB_ENV  # Starting version if no tag exists
        else
          # Increment minor version or other logic
          IFS='.' read -r major minor patch <<< "${{ env.latest_tag#v}}"
          minor=$((minor + 1))
          new_tag="v${major}.${minor}.${patch}"
          echo "new_tag=${new_tag}" >> $GITHUB_ENV
        fi

    - name: Generate tag description
      id: generate_description
      run: |
        if [ -z "${{ env.latest_tag }}" ]; then
          echo "description=Initial release." >> $GITHUB_ENV
        else
          # Get commit messages since the last tag
          commit_messages=$(git log "${{ env.latest_tag }}..HEAD" --pretty=format:"%s" | tr '\n' ', ')
          echo "description=Changes: $commit_messages" >> $GITHUB_ENV
        fi

    - name: Tag and push
      run: |
        git tag -a ${{ env.new_tag }} -m "${{ env.description }}"
        git push origin ${{ env.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default token
